default_stages: [pre-commit]
default_language_version:
  python: python3
fail_fast: false

exclude: ^experiments/|^tests/|^notebooks/

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=6000']
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
      - id: flake8

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.1
    hooks:
      - id: ruff-format
      - id: ruff
        args: [--fix]

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        language: system
        entry: >-
          bash -c 'git ls-files "*.py" | grep -v "^experiments/" | grep -v "^tests/" | xargs uv run pylint'
        types_or: [python, pyi]
        pass_filenames: false
