# hmc-torch hyperparameter configuration (ArXiv and WOS datasets only).
datasets_params:
  arxiv:
    hidden_dims: [512]
    lr_values: [0.0001]
    dropout_values: [0.3]
    num_layers_values: [3]
    weight_decay_values: [0.00001]
  wos:
    hidden_dims: [512]
    lr_values: [0.0001]
    dropout_values: [0.3]
    num_layers_values: [3]
    weight_decay_values: [0.00001]
